fix all update methods on SDK to avoid updating unexpected attributes.
tsubaiso/tsubaiso-sdk-ruby pull request #48
Opened 2019-06-13 08:03 UTC by Pyons04

SDKテストから送られるupdateパラメータのうち、ユーザーが指定したパラメータだけupdateを掛ける様改善し、残りのパラメータがnilで上書きされるのを防ぎます。

2019-06-27 09:01 UTC, creep1986 requested changes

2019-06-27 09:01 UTC, creep1986 commented on lib/tsubaiso_sdk.rb
> +  def checking_keys_and_values(keys,options)
このメソッドは privateメソッドにしましょう。定義をファイルの一番下に移動してください。

2019-06-27 09:01 UTC, creep1986 commented on lib/tsubaiso_sdk.rb
> +  def checking_keys_and_values(keys,options)
名前は `checking_...` ですが、実際にやっていることはパラメータの作成なので、`make_parameters` のような名称がいいのではないでしょうか。

また、このメソッドはupdate系だけでなくcreate系でも使用する方がいいです。
createでも、オプションパラメータが渡されなかったときにデフォルト値を使用する場合があります。 nil を明示的にいれてしまうとデフォルト値を使用してもらえなくなり、ユーザーの意図しない動作をする可能性があります。

2019-06-27 09:01 UTC, creep1986 commented on lib/tsubaiso_sdk.rb
> +    return params
今のままでも問題ないんですが、↓このように書いても同じ動作になると思います。どうでしょうか？
```
(keys & options.keys).inject({ 'format' => 'json' }) do |params, key|
    params.merge(key => options[key])
end

```
もっとシンプルに書きたいですが、Hash#sliceはruby 2.5.0からなので。。。

2019-07-19 06:12 UTC, Pyons04 commented on lib/tsubaiso_sdk.rb
> +  def checking_keys_and_values(keys,options)
* メソッド名をreate_parametersに変更し、privateメソッドとしました。
* create系のメソッドでも同様のことを行うようにしました。ただし、この方法だとネストしたjsonの形成に関しては処理が複雑になるため、create_journal_distributionに関しては従来の方法でjsonを形成してます。

2019-07-19 06:13 UTC, Pyons04 commented on lib/tsubaiso_sdk.rb
> +    return params
教えていただいたコードに変更しました。

2020-01-06 02:26 UTC, Pyons04 commented
merged manually to create_SDK_stub_with_json

2020-01-06 02:26 UTC, closed without merging